development:
  adapter: mysql
  database: propelledby_development
  username: root
  password: 
  host: localhost
test:
  adapter: mysql
  database: propelledby_test
  username: root
  password: 
  host: localhost
production:
  adapter: mysql
  database: propelledby_production
  username: root
  password: 
  host: localhost